# Helper to format comments with structured markdown sections
def build_markdown_comment(text: str) -> str:
    """Build formatted markdown comment with header"""
    header = """## Automated AI Code Review
*This review was generated by the AI PR Reviewer Bot.*

---

"""
    return header + text

def build_summary_comment(title: str, highlights: str, issues: str, suggestions: str) -> str:
    """Build structured review comment from components"""
    comment = f"""## Automated AI Code Review

### Summary
{title}

### Highlights
{highlights}

### Issues & Concerns
{issues}

### Suggestions
{suggestions}

---
*Generated by AI PR Reviewer Bot*
"""
    return comment
